---

#
# variables shared in baselayout
#

ssh_config: /etc/ssh/sshd_config

sshd_service_name: 'sshd'

ntp_service: {
  systemd: ['debian8', 'ubuntu1604', 'ubuntu1804', 'ubuntu2204', 'ubuntu2404']
}

common_packages: [
]

# you can either add os family or os to this list (see smartos)
# but the playbook chooses os over family - not both
packages: {
  ubuntu2404: [
    'docker.io',
  ],
  ubuntu2204: [
    'docker.io',
  ],
  ubuntu2004: [
    'docker.io',
  ],
  ubuntu1804: [
    'docker-ce',
  ],
}

tap2junit_version: 0.2.0
