---

#
# variables shared in baselayout
#

ssh_config: /etc/ssh/sshd_config

sshd_service_map: {
  'ubuntu1404': 'ssh',
}

sshd_service_name: "{{ sshd_service_map[os]|default(sshd_service_map[os|stripversion])|default('sshd') }}"

ntp_service: {
  systemd: ['debian8', 'debian9', 'debian10', 'ubuntu1604', 'ubuntu1804'],
  ntp_package: ['ubuntu1404']
}

common_packages: [
]

# you can either add os family or os to this list (see smartos)
# but the playbook chooses os over family - not both
packages: {
  ubuntu2004: [
    'docker.io',
  ],
  ubuntu1804: [
    'docker-ce',
  ],
}

tap2junit_version: 0.1.6
