---

#
# variables shared in baselayout
#

ssh_config: /etc/ssh/sshd_config

sshd_service_map: {
  'ubuntu1404': 'ssh',
}

sshd_service_name: "{{ sshd_service_map[os]|default(sshd_service_map[os|stripversion])|default('sshd') }}"

ntp_service: {
  systemd: [ 'debian8', 'debian9', 'ubuntu1604', 'ubuntu1610', 'ubuntu1710' ],
  ntp_package: [ 'ubuntu1404' ]
}

common_packages: [
]

# you can either add os family or os to this list (see smartos)
# but the playbook chooses os over family - not both
packages: {
  ubuntu: [
    'docker-ce',
  ],
}
