---

#
#
#

  pm: {
    'yum': ['centos', 'rhel7', 'ibmi'],
    'apt': ['debian', 'ubuntu'],
    'dnf': ['aix72', 'aix73', 'fedora', 'rhel8', 'rhel9'],
    'pkgng': 'freebsd',
    'pkgin': 'smartos',
    'chocolatey': 'win',
    'brew': 'macos'
    }

  # see plugins/filter/filters.py -- second arg is just feedback
  # if you fail here you need to add your package manager
  template: "{{ os|match_key(pm) }}"
