---

#
# installs java
#

- name: install add-apt-repostory
  when: os == "ubuntu1404" and arch != "ppc64"
  package: name=software-properties-common state=present

- name: add webupd8 oracle java repository
  when: os == "ubuntu1404" and arch != "ppc64"
  apt_repository: repo='ppa:webupd8team/java'

- name: add webupd8team oracle java repository
  when: os == "debian8"
  lineinfile:
    dest: /etc/apt/sources.list
    state: present
    line: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main

- name: add webupd8team oracle java repository key
  when: os == "debian8"
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886

- name: accept webupd8 oracle java 8 license
  when: os == "ubuntu1404" and arch != "ppc64" or os == "debian8"
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: update packages
  when: arch != "ppc64"
  include_role:
    name: package-upgrade

- name: download java ppc64
  when: os in ("ubuntu1404", "centos7") and arch == "ppc64"
  get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u172-b11/OpenJDK8_ppc64le_Linux_jdk8u172-b11.tar.gz
    dest: /tmp/

- name: unarchive java ubuntu1404 ppc64
  when: os in "ubuntu1404" and arch == "ppc64"
  unarchive:
    src: /tmp/OpenJDK8_ppc64le_Linux_jdk8u172-b11.tar.gz
    remote_src: true
    dest: /home/iojs
  tags: java

- name: unarchive java centos7 ppc64
  when: os in "centos7" and arch == "ppc64"
  unarchive:
    src: /tmp/OpenJDK8_ppc64le_Linux_jdk8u172-b11.tar.gz
    remote_src: yes
    dest: /opt
  tags: java

- name: symlink java centos7 ppc64
  when: os in "centos7" and arch == "ppc64"
  file:
    src: "/opt/jdk8u172-b11/bin/java"
    dest: "/usr/bin/java"
    state: link

- name: download java on s390x
  when: os == "rhel7" and arch == "s390x"
  get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08_openj9-0.18.1/OpenJDK8U-jdk_s390x_linux_openj9_8u242b08_openj9-0.18.1.tar.gz
    dest: /tmp/
- name: unarchive java s390x
  when: os == "rhel7" and arch == "s390x"
  unarchive:
    src: /tmp/OpenJDK8U-jdk_s390x_linux_openj9_8u242b08_openj9-0.18.1.tar.gz
    remote_src: yes
    dest: /opt
  tags: java

- name: symlink java s390x
  when: os == "rhel7" and arch == "s390x"
  file:
    src: "/opt/jdk8u242-b08/bin/java"
    dest: "/usr/bin/java"
    state: link

# if this fails you want to check in vars/main.yml and add package name
# as appropriate -- try to use generic os family if available.

- name: Check if java is already installed
  raw: java -version
  register: java
  ignore_errors: true

- name: install java
  when:
    - java.rc > 0 and not os|startswith("zos") and arch != "ppc64"
    - java.rc > 0 and not os|startswith("macos")
  package: name="{{ java_package_name }}" state=present

- name: install java tap (macOS)
  become_user: administrator
  when: java.rc > 0 and os|startswith("macos")
  homebrew_tap:
        name: AdoptOpenJDK/openjdk
        state: present

- name: install java (macOS)
  become_user: administrator
  when: java.rc > 0 and os|startswith("macos")
  homebrew_cask:
        name: "{{ java_package_name }}"
        state: present

- name: check if java is installed AIX
  stat:
    path: /home/iojs/jdk8u192-b12-jre/bin
  register: java_exists
  when: os|startswith("aix")

- name: download java AIX
  get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jre_ppc64_aix_hotspot_8u192b12.tar.gz
    dest: /tmp/
  tags: java
  when: os|startswith("aix") and java_exists.stat.exists == False

- name: unarchive java AIX
  unarchive:
    src: /tmp/OpenJDK8U-jre_ppc64_aix_hotspot_8u192b12.tar.gz
    remote_src: yes
    dest: /home/iojs
  tags: java
  when: os|startswith("aix") and java_exists.stat.exists == False

- name: install webupd8 oracle java 8 extras
  when: java.rc > 0 and os == "ubuntu1404" and arch != "ppc64"
  package: name="{{item}}" state=present
  with_items:
    - ca-certificates
    - oracle-java8-set-default
