---

#
# Install packages for V8 builds.
#

# Older V8 builds still require Python 2.
# rhel_llvm_version and rhel_rust_version from ansible/roles/baselayout/vars/main.yml
- name: install packages required to build V8
  ansible.builtin.dnf:
    name: ['GConf2-devel', 'bindgen-cli', 'llvm-toolset-{{rhel_llvm_version}}', 'python2', 'python2-pip', 'rustfmt-{{rhel_rust_version}}']
    state: present
  notify: package updated

- name: update python package alternatives
  community.general.alternatives:
    link: /usr/bin/python
    name: python
    path: /usr/bin/python2

- name: install dependencies for V8 build tools (Python 2)
  ansible.builtin.pip:
    executable: pip2
    name: httplib2
    state: present

- name: install dependencies for V8 build tools (Python 3)
  ansible.builtin.pip:
    executable: pip-3
    name: ['filecheck', 'httplib2', 'six']
    state: present
