---

#
# installs gcc 4.9 @ /data/gcc-4.9 on rhel7.x
# and      gcc 6.3 @ /data/gcc-6.3
#


## gmp-6.1

- stat: path=/data/gmp-6.1/include/gmp.h
  register: build_gmp
  tags: gcc

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_gmp.stat.exists == False
  tags: gcc


- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_gmp.stat.exists == False
  tags: gcc

- name: download gmp 6.1.0
  get_url:
    url: http://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.xz
    dest: /data/tmp/
  when: build_gmp.stat.exists == False
  tags: gcc

- name: unarchive gmp 6.1.0
  unarchive:
    src: /data/tmp/gmp-6.1.0.tar.xz
    remote_src: true
    dest: /data/tmp/
  when: build_gmp.stat.exists == False
  tags: gcc

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_gmp.stat.exists == False
  tags: gcc

- name: configure gmp 6.1.0
  shell: /data/tmp/gmp-6.1.0/configure --prefix=/data/gmp-6.1
  args:
    chdir: /data/tmp/build
  when: build_gmp.stat.exists == False
  tags: gcc

- name: build gmp 6.1.0
  shell: make -j{{ ansible_processor_cores }} install
  args:
    chdir: /data/tmp/build
  when: build_gmp.stat.exists == False
  tags: gcc


## mpfr-3.1

- stat: path=/data/mpfr-3.1/include/mpfr.h
  register: build_mpfr
  tags: gcc

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: download mprf 3.1.4
  get_url:
    url: http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.4.tar.gz
    dest: /data/tmp/
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: unarchive mprf 3.1.4
  unarchive:
    src: /data/tmp/mpfr-3.1.4.tar.gz
    remote_src: true
    dest: /data/tmp/
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: build mprf 3.1.4
  shell: /data/tmp/mpfr-3.1.4/configure --with-gmp=/data/gmp-6.1 --prefix=/data/mpfr-3.1
  args:
    chdir: /data/tmp/build
  when: build_mpfr.stat.exists == False
  tags: gcc

- name: build mprf 3.1.4
  shell: make -j{{ ansible_processor_cores }} install
  args:
    chdir: /data/tmp/build
  when: build_mpfr.stat.exists == False
  tags: gcc

## mpc-1.0

- stat: path=/data/mpc-1.0/include/mpc.h
  register: build_mpc
  tags: gcc

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_mpc.stat.exists == False
  tags: gcc


- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_mpc.stat.exists == False
  tags: gcc

- name: download mpc 1.0.3
  get_url:
    url: http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
    dest: /data/tmp/
  when: build_mpc.stat.exists == False
  tags: gcc

- name: unarchive mpc 1.0.3
  unarchive:
    src: /data/tmp/mpc-1.0.3.tar.gz
    remote_src: true
    dest: /data/tmp/
  when: build_mpc.stat.exists == False
  tags: gcc

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_mpc.stat.exists == False
  tags: gcc

- name: configure mpc 1.0.3
  shell: /data/tmp/mpc-1.0.3/configure --with-mpfr=/data/mpfr-3.1 --with-gmp=/data/gmp-6.1 --prefix=/data/mpc-1.0
  args:
    chdir: /data/tmp/build
  when: build_mpc.stat.exists == False
  tags: gcc

- name: build mpc 1.0.3
  shell: make -j{{ ansible_processor_cores }} install
  args:
    chdir: /data/tmp/build
  when: build_mpc.stat.exists == False
  tags: gcc


## binutils-2.28

- stat: path=/data/binutils-2.28/bin/ranlib
  register: build_binutils
  tags: gcc

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_binutils.stat.exists == False
  tags: gcc

- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_binutils.stat.exists == False
  tags: gcc

- name: download binutils 2.28.1
  get_url:
    url: https://ftp.gnu.org/gnu/binutils/binutils-2.28.1.tar.gz
    dest: /data/tmp/
  when: build_binutils.stat.exists == False
  tags: gcc

- name: unarchive binutils 2.28.1
  unarchive:
    src: /data/tmp/binutils-2.28.1.tar.gz
    remote_src: true
    dest: /data/tmp/
  when: build_binutils.stat.exists == False
  tags: gcc

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_binutils.stat.exists == False
  tags: gcc

- name: configure binutils 2.28.1
  shell: /data/tmp/binutils-2.28.1/configure --with-mpfr=/data/mpfr-3.1 --with-gmp=/data/gmp-6.1 --prefix=/data/binutils-2.28
  args:
    chdir: /data/tmp/build
  when: build_binutils.stat.exists == False
  tags: gcc

- name: build binutils 2.28.1
  shell: make -j{{ ansible_processor_cores }}
  args:
    chdir: /data/tmp/build
  when: build_binutils.stat.exists == False
  tags: gcc

- name: install binutils 2.28.1
  shell: make install
  args:
    chdir: /data/tmp/build
  when: build_binutils.stat.exists == False
  tags: gcc


## gcc-4.9

- stat: path=/data/gcc-4.9/bin/gcc-4.9
  register: build_gcc_49
  tags: gcc49

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: download gcc 4.9.4
  get_url:
    url: http://ftp.gnu.org/gnu/gcc/gcc-4.9.4/gcc-4.9.4.tar.gz
    dest: /data/tmp/
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: unarchive gcc 4.9.4
  unarchive:
    src: /data/tmp/gcc-4.9.4.tar.gz
    remote_src: true
    dest: /data/tmp/
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: configure gcc4.9
  shell: /data/tmp/gcc-4.9.4/configure --with-mpfr=/data/mpfr-3.1 --with-gmp=/data/gmp-6.1 --with-mpc=/data/mpc-1.0 --prefix=/data/gcc-4.9 --program-suffix=-4.9 --disable-multilib
  args:
    chdir: /data/tmp/build
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: build gcc49
  shell: make -j{{ ansible_processor_cores }}
  async: 3600
  poll: 10
  args:
    chdir: /data/tmp/build
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: install gcc49
  shell: make install
  args:
    chdir: /data/tmp/build
  when: build_gcc_49.stat.exists == False
  tags: gcc49

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_gcc_49.stat.exists == False
  tags: gcc49


## gcc-6.3

- stat: path=/data/gcc-6.3/bin/gcc-6.3
  register: build_gcc_63
  tags: gcc63

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: Create working directory
  file:
    path: /data/tmp
    state: directory
    mode: 0755
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: download gcc 6.3.0
  get_url:
    url: http://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.gz
    dest: /data/tmp/
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: unarchive gcc 6.3.0
  unarchive:
    src: /data/tmp/gcc-6.3.0.tar.gz
    remote_src: yes
    dest: /data/tmp/
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: Create build directory
  file:
    path: /data/tmp/build
    state: directory
    mode: 0755
  when: build_gcc_63.stat.exists == False
  tags: gcc63

# gcc6.3 needs a g++ with '-no-pie', and system default of 4.8 does not
- name: configure gcc6.3
  shell: CC=/data/gcc-4.9/bin/gcc-4.9 CXX=/data/gcc-4.9/bin/g++-4.9 /data/tmp/gcc-6.3.0/configure --with-mpfr=/data/mpfr-3.1 --with-gmp=/data/gmp-6.1 --with-mpc=/data/mpc-1.0 --prefix=/data/gcc-6.3 --program-suffix=-6.3 --disable-multilib
  args:
    chdir: /data/tmp/build
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: build gcc63
  shell: make -j{{ ansible_processor_cores }}
  async: 7000
  poll: 10
  args:
    chdir: /data/tmp/build
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: install gcc63
  shell: make install
  args:
    chdir: /data/tmp/build
  when: build_gcc_63.stat.exists == False
  tags: gcc63

- name: Clean path
  file:
    state: absent
    path: /data/tmp/
  when: build_gcc_63.stat.exists == False
  tags: gcc63
