---
- hosts: iojs-raspbian
  sudo: yes

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | APT Update
      apt:
        update_cache: yes
      tags: general

    - name: General | APT Upgrade
      apt:
        upgrade: dist
      tags: general

    - name: General | Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items: packages
      tags: general

    - name: General | update-alternatives for gcc
      alternatives:
        name: "{{ item.link }}"
        link: "/usr/bin/{{ item.link }}"
        path: "/usr/bin/{{ item.path }}"
      with_items:
        - { link: 'gcc', path: 'gcc-4.8' }
        - { link: 'cc', path: 'gcc-4.8' }
        - { link: 'g++', path: 'g++-4.8' }
        - { link: 'c++', path: 'g++-4.8' }
        - { link: 'cpp', path: 'g++-4.8' }
      tags: general

    - name: General | Increase file descriptor limits
      lineinfile:
        dest: /etc/security/limits.conf
        line: "{{ item }}"
      with_items:
        - "*         hard    nofile      500000"
        - "*         soft    nofile      500000"
        - "root      hard    nofile      500000"
        - "root      soft    nofile      500000"
      tags: general

    - name: User | Add {{ server_user }} user
      user:
        name: "{{ server_user }}"
        shell: /bin/bash
      tags: user

    - name: User | Download pubkey(s)
      get_url:
        url: "https://github.com/{{ item }}.keys"
        dest: "/tmp/{{ item }}.keys"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for {{ server_user }}
      authorized_key: user="{{ server_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins' slave.jar to {{ server_user }}
      command: curl -sL https://ci.nodejs.org/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: NFS | Make NFS mounted directories
      file:
        path: "/home/{{ server_user }}/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ server_user }}"
      with_items:
        - ".ccache"
        - "build"
      ignore_errors: True
      tags: nfs

    - name: NFS | Add directories to /etc/fstab
      lineinfile:
        dest: /etc/fstab
        line: "{{ item }}"
      with_items:
        - "{{ nfs_server }}:{{ nfs_share_root }}/.ccache /home/{{ server_user }}/.ccache nfs defaults 0 1"
        - "{{ nfs_server }}:{{ nfs_share_root }}/{{ server_id }} /home/{{ server_user }}/build nfs defaults 0 1"
      tags: nfs

    - name: NFS | Mount all
      command: mount -a
      tags: nfs

    - name: Jenkins | Download Jenkins' slave.jar to {{ server_user }}
      command: curl -sL https://ci.nodejs.org/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Copy start.sh script
      copy:
        src: "./resources/start.sh"
        dest: "/home/{{ server_user }}/start.sh"
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: 0755
      tags: jenkins

    - name: Jenkins | Copy variables to start.sh script
      replace:
        dest: "/home/{{ server_user }}/start.sh"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: '\{\{server_secret\}\}', replace: '{{ server_secret }}' }
        - { regexp: '\{\{server_id\}\}', replace: '{{ server_id }}' }
        - { regexp: '\{\{server_suffix\}\}', replace: '{{ server_suffix }}' }
        - { regexp: '\{\{server_arch\}\}', replace: '{{ server_arch }}' }
      tags: jenkins

    - include: ../ansible-tasks/ccache.yaml version=3.2.3
      tags: ccache

    - include: ../ansible-tasks/git.yaml version=2.5.0
      tags: git

    - include: ../ansible-tasks/monit.yaml monit_conf_file=../ansible-tasks/resources/monit-jenkins.conf
      tags: monit

