---

- name: GitHub Webhook | Install github-webhook
  command: "npm install github-webhook -g"
  tags: webhook

- name: GitHub Webhook | Copy config
  template:
    src: ./resources/config/github-webhook.json.j2
    dest: /etc/github-webhook.json
    mode: 0644
  tags: webhook

- name: GitHub Webhook | Generate and copy init script
  template:
    src: ./resources/config/github-webhook.service.j2
    dest: /lib/systemd/system/github-webhook.service
  tags: webhook

- name: GitHub Webhook | Start service
  service:
    name: github-webhook
    state: restarted
    enabled: true
  tags: webhook
