---
- hosts: iojs-build-ubuntu1404

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | APT Update and upgrade
      apt: update_cache=yes upgrade=full
      tags: general

    - name: General | Install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items: packages
      tags: general

    - name: NTP | Run initial NTP
      command: ntpdate -u pool.ntp.org
      tags: ntp

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: Clone the gyp git repo
      git: repo=https://chromium.googlesource.com/external/gyp dest=/home/iojs/gyp
      tags: gyp

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.conf.j2 dest=/etc/init/jenkins.conf
      tags: init

    - name: Init | Start Jenkins
      service: name=jenkins state=started enabled=yes
      tags: init
