---

#
# sets up the host that runs the github-bot
#
# To properly run with secrets, copy and paste the YAML from
# `build/github-bot/deployment_secrets.md` in the `nodejs/secrets` repo into
# `ansible/host_vars/infra-rackspace-debian9-x64-1` in this repo (nodejs/build)
#

- hosts: infra-rackspace-debian9-x64-1
  roles:
    - bootstrap
    - package-upgrade
    - github-bot
  pre_tasks:
    - name: check if secrets are properly set
      fail:
      failed_when: not {{ secret }}
      loop_control:
        loop_var: secret
      with_items:
        - envs.port
        - envs.travis_token
        - envs.github_token
        - envs.github_webhook_secret
        - envs.login_credentials
        - envs.jenkins_api_credentials
        - envs.jenkins_job_citgm
        - envs.jenkins_build_token_citgm
        - envs.jenkins_job_node
        - envs.jenkins_build_token_node
        - conf.github_deploy_webhook_secret
