---

#
# centos5: python2.4 is default -- python 2.6 is available through epel
#

- name: install required packages
  package: name="{{ package }}" state=present
  loop_control:
    loop_var: package
  with_items:
    - python26-setuptools
    - python26-argparse

- name: install tap2junit
  raw: easy_install tap2junit
