---

#
# install tap2junit ibmi
#

- name: install tap2junit
  pip:
    name: tap2junit=={{ tap2junit_version }}
    virtualenv: /home/{{ server_user|upper }}/venv
    virtualenv_command: python3.13 -m venv
