---

#
# install tap2junit ibmi
#

- name: install tap2junit
  ansible.builtin.pip:
    executable: /QOpenSys/pkgs/bin/pip3.13
    name: tap2junit
    state: present
    version: "{{ tap2junit_version }}"
