---

#
# rhel72: python2.7 is default
#

- name: install required packages
  package: name="{{ package }}" state=present
  loop_control:
    loop_var: package
  with_items:
    - python-setuptools

- name: install tap2junit
  raw: easy_install tap2junit
