----
- hosts: iojs-freebsd10
  gather_facts: no
  remote_user: freebsd
  sudo: yes

  vars_files:
    - ../ansible-includes/global-vars.yaml
    - ansible-vars.yaml

  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - name: Bootstrap | Install python
      raw: pkg install -y python
      tags: bootstrap

    - name: General | Install required packages
      command: pkg install -y {{ item }}
      with_items: packages
      tags: general

    - name: General | Start ntpd (and enable at boot)
      service: name=ntpd state=started enabled=yes
      tags: general

    - name: User | Add group
      group: name="{{ jenkins_user }}" state=present
      tags: user

    - name: User | Add user
      user: name="{{ jenkins_user }}" shell=/bin/sh createhome=yes append=yes groups={{ jenkins_user }}
      tags: user

    - name: User | Download pubkey(s)
      get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.keys
      delegate_to: 127.0.0.1
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for root
      authorized_key: user="root" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for user
      authorized_key: user="{{ jenkins_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url={{ jenkins_base_url }}/jnlpJars/slave.jar dest=/home/{{ jenkins_user }}/slave.jar
      tags: jenkins

    - name: Init | Assure that {rc.d, rc.conf.d} directories exists
      file: path={{ init_base }}/{{ item }} state=directory
      with_items:
        - rc.d
        - rc.conf.d
      tags: init

    - name: Init | Copy init script
      copy: src=./resources/jenkins dest={{ init_base }}/rc.d/jenkins mode=0755
      tags: init

    - name: Init | Generate config
      template: src=./resources/jenkins.conf.j2 dest={{ init_base }}/rc.conf.d/jenkins
      tags: init

    - name: Init | Add to boot and start service
      service: name=jenkins state=started enabled=yes
      tags: init
