---

#
# create linters
#

- hosts:
   - test-joyent-freebsd10-x64-2
   - test-rackspace-freebsd10-x64-1

  roles:
    - bootstrap
    - baselayout
    - package-upgrade
    - jenkins-worker

  vars:
    - linter_packages: [ 'node', 'npm' ]

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret

  tasks:
    - name: install lint-related packages
      package: name="{{ package }}" state=present
      loop_control:
        loop_var: package
      with_items: "{{ linter_packages }}"

    - name: install "core-validate-commit"
      npm: name="core-validate-commit" global=yes state=present production=yes


    - name: periodically update "core-validate-commit"
      cron:
        special_time: daily
      # ksh does different stdout/err routing
        job: "npm update -g core-validate-commit > & /dev/null"
