---
- hosts: iojs-build-rhel72-linuxonecc

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | yum Update
      yum: name=* state=latest
      tags: general

    - name: General | Install required packages
      yum: name={{ item }} state=latest
      with_items: packages
      tags: general

    - name: NTP | Run initial NTP
      command: ntpdate -u pool.ntp.org
      tags: ntp

    - name: NTP | Start NTP
      service: name=ntpd state=started enabled=yes
      tags: ntp

    - name: User | create file system on larger disk
      filesystem: fstype=ext4 dev=/dev/dasdb1

    - name: User | ensure larger disk is mounted
      mount: name=/data src=/dev/dasdb1 fstype=ext4 state=mounted

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash home=/data/iojs
      tags: user

    - name: User | Download pubkey(s)
      get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.keys
      delegate_to: 127.0.0.1
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for root
      authorized_key: user="root" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for {{ server_user }}
      authorized_key: user="{{ server_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/data/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.service.j2 dest=/usr/lib/systemd/system/jenkins.service mode=0644
      tags: init

    - name: Jenkins | Start Jenkins service
      service: name=jenkins state=started enabled=yes
      tags: jenkins
