---

#
# alpine3 repos - these are required in bootstrap so they're probably in place
#

- name: "repos : add alpine edge package repos"
  when: not has_added_package_repo
  lineinfile: dest=/etc/apk/repositories create=yes line="{{ item }}"
  with_items:
    - https://dl-3.alpinelinux.org/alpine/edge/main
    - https://dl-3.alpinelinux.org/alpine/edge/community

- name: "repos : update repo"
  raw: apk update -q
