---

#
# add backports for gcc 4.8
#


- name: "repo : add wheezy-backports"
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian wheezy-backports main'
    state: present
    update_cache: true
  register: has_updated_package_repo
