---

- name: "debian8 | add debian-backports"  # has systemd-coredump if needed
  apt_repository:
    repo: 'deb http://archive.debian.org/debian jessie-backports main'
    state: present
    update_cache: true
  register: has_updated_package_repo

- name: "debian8 | add git-core trusty ppa"
  apt_repository:
    repo: ppa:git-core/ppa
    codename: trusty
    state: present
    update_cache: true
  register: has_updated_package_repo

- name: "debian8 | add trusty-updates gpg keys"
  shell: "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com {{ item }}"
  with_items:
    - 40976EAF437D05B5
    - 3B4FE6ACC0B21F32
  register: has_updated_package_repo

- name: "debian8 | install lower trusty-updates package priority"
  copy:
    src: "{{ role_path }}/files/debian8-ubuntu-trusty-apt-preferences"
    dest: "/etc/apt/preferences.d/trusty-updates"
    mode: 0644
  register: has_updated_package_repo

- name: "debian8 | add trusty-updates"
  apt_repository:
    repo: 'deb http://us.archive.ubuntu.com/ubuntu trusty-updates main universe'
    state: present
    update_cache: true
  register: has_updated_package_repo
