---

# Red Hat Enterprise Linux 9

- name: install GPG key for EPEL 9
  become: yes
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    state: present

- name: install EPEL 9
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: install Python 3.12
  ansible.builtin.dnf:
    name: ['python3.12','python3.12-pip']
    state: present
  notify: package updated

- name: update python3 package alternatives
  community.general.alternatives:
    link: /usr/bin/python3
    name: python3
    path: /usr/bin/python3.12
