---

#
# installs and starts monit
#

- name: install monit
  package: name=monit state=present

- name: add monit config
  copy:
  args:
    src: "{{ monitrc }}"
    dest: "/etc/monit.d/jenkins"
    mode: 0440
  loop_control:
    loop_var: monitrc
  with_first_found:
    - files:
        - "{{ role_path }}/files/{{ os }}.monitrc"
        - "{{ role_path }}/files/{{ os|stripversion }}.monitrc"

- name: start monit on boot
  service: name=monit enabled=yes state=started
