---
- hosts: iojs-armv7-wheezy

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: Install Raspbian GPG key
      shell: "wget http://archive.raspberrypi.org/debian/raspberrypi.gpg.key -O - | sudo apt-key add -"
      tags: general

    - name: Install Raspbian APT sources
      lineinfile: dest=/etc/apt/sources.list line="{{ item }}"
      with_items:
        - "deb http://archive.raspberrypi.org/debian/ wheezy main"
      tags: general

    - name: General | APT Update
      apt: update_cache=yes
      tags: general

    - name: General | APT Upgrade
      apt: upgrade=dist
      tags: general

    - name: General | Install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items: packages
      tags: general

    - name: General | Install required packages from wheezy-backports
      apt: name={{ item }} update_cache=yes state=latest default_release=wheezy-backports
      with_items: backports_packages
      tags: general

    - name: General | update-alternatives for gcc
      alternatives: name=gcc link=/usr/bin/gcc path=/usr/bin/gcc-4.8
      tags: general

    - name: General | update-alternatives for cc
      alternatives: name=cc link=/usr/bin/cc path=/usr/bin/gcc-4.8
      tags: general

    - name: General | update-alternatives for g++
      alternatives: name=g++ link=/usr/bin/g++ path=/usr/bin/g++-4.8
      tags: general

    - name: General | update-alternatives for c++
      alternatives: name=c++ link=/usr/bin/c++ path=/usr/bin/g++-4.8
      tags: general

    - name: General | update-alternatives for cpp
      alternatives: name=cpp link=/usr/bin/cpp path=/usr/bin/g++-4.8
      tags: general

    - name: General | Increase file descriptor limits
      lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
      with_items:
        - "*         hard    nofile      500000"
        - "*         soft    nofile      500000"
        - "root      hard    nofile      500000"
        - "root      soft    nofile      500000"
      tags: general

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: User | Download pubkey(s)
      get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.keys
      delegate_to: 127.0.0.1
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for root
      authorized_key: user="root" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for {{ server_user }}
      authorized_key: user="{{ server_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins' slave.jar
      command: curl -sL https://jenkins-iojs.nodesource.com/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Copy start.sh script
      copy: src=./resources/start.sh dest=/home/{{ server_user }}/start.sh owner={{ server_user }} group={{ server_user }} mode=0755
      tags: jenkins

    - name: Jenkins | Copy secrets to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{secret\}\}" replace="{{ server_secret }}"
      tags: jenkins

    - name: Jenkins | Copy server ids to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{id\}\}" replace="{{ server_id }}"
      tags: jenkins

    - include: ../ansible-tasks/ccache.yaml version=3.2.3
      tags: ccache

    - include: ../ansible-tasks/git.yaml version=2.5.0
      tags: git

    - name: Monit | Copy monit config
      copy: src=./resources/monit-jenkins.conf dest=/etc/monit/conf.d/jenkins owner=root group=root mode=0644
      tags: monit

    - name: Monit | Restart service
      service: name=monit state=restarted
      tags: monit
