---

argument_specs:
  main:
    short_description: Set up specific to hosts that need to interact with github.com.
    options:
      user_home_dir:
        description: The user's HOME directory.
        required: yes
        type: str
